id: P005438
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W2CZ6606
  title: རྭ་ལོ་ཙ་བའི་རྣམ་ཐར་ཀུན་ཁྱབ་སྙན་པའི་རྔ་སྒྲ་
  author: ''
  volumes:
    5a82586be6544f1c9aba975dfad316d7:
      image_group_id: I1KG1454
      title: ''
      volume_number: 1
      total_pages: 304
      base_file: v001.txt
